parameters:
#    epiphany_service_cache.example.class: Epiphany\ServiceCacheBundle\Example

services:
#    epiphany_service_cache.example:
#        class: %epiphany_service_cache.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
